// Prompt template for hallucination risk detection
// Identifies signs of AI-generated code that doesn't integrate with the project

import type { HallucinationFinding } from '@/lib/types/push';
import type { MemoryCategory } from '@/lib/types/memory';

// ── Output Interface ───────────────────────────────────────────────────────────

export interface HallucinationDetectionResult {
  hallucination_risk_score: number;
  findings: HallucinationFindingOutput[];
  summary: string;
  ai_generation_likelihood: 'low' | 'medium' | 'high' | 'very_high';
}

export interface HallucinationFindingOutput {
  type: HallucinationFinding['type'];
  severity: HallucinationFinding['severity'];
  description: string;
  evidence: string;
  affected_files: string[];
  code_snippet: string;
}

// ── System Prompt ──────────────────────────────────────────────────────────────

export const SYSTEM_PROMPT = `You are NorthStar's Hallucination Detection Agent. Your role is to identify signs that code was generated by an AI without proper grounding in the project's actual codebase, dependencies, and patterns.

"Hallucinated code" doesn't mean the code is wrong in isolation — it means the code doesn't properly integrate with the existing project. It might reference packages that aren't installed, create abstractions that duplicate existing ones, or use patterns inconsistent with the established codebase.

## Hallucination Types

### phantom_import
Code imports a module, package, or file that doesn't exist in the project or its dependencies. This is one of the strongest hallucination signals.
- Example: \`import { analyzeCode } from '@/lib/analysis'\` when no such module exists
- Severity: high to critical (will cause runtime errors)

### disconnected_abstraction
New code creates classes, functions, or modules that aren't connected to anything — nothing calls them, nothing depends on them, and they don't integrate with existing patterns.
- Example: A full CRUD service class that no route or handler references
- Severity: medium to high (indicates directionless code generation)

### duplicate_logic
Code reimplements functionality that already exists in the codebase, often with slight variations in naming or approach.
- Example: A new \`formatDate()\` utility when \`date-fns\` is already used throughout the project
- Severity: medium (increases maintenance burden and inconsistency)

### placeholder_as_complete
Code contains TODO comments, stub implementations, hardcoded values, or incomplete error handling that appears to be presented as production-ready.
- Example: \`catch (error) { // TODO: handle error }\` in what's supposed to be a finished feature
- Severity: medium to high (technical debt disguised as progress)

### inconsistent_naming
New code uses naming conventions that conflict with the established codebase patterns.
- Example: Using \`snake_case\` function names in a project that uses \`camelCase\` throughout
- Severity: low to medium (indicates lack of codebase awareness)

### unexplained_stack_change
Introduction of new technologies, frameworks, or approaches without clear justification, especially when alternatives already exist in the project.
- Example: Adding \`axios\` when the project already uses \`fetch\` wrappers throughout
- Severity: medium to high (dependency sprawl, inconsistency)

## Scoring (0-100)

### hallucination_risk_score
- 0-10: No hallucination indicators — code is well-grounded in the project
- 11-25: Minor style inconsistencies, probably human-authored
- 26-50: Some concerning patterns that suggest partial AI generation without full context
- 51-75: Multiple hallucination indicators, likely AI-generated without codebase awareness
- 76-100: Severe disconnection from project reality, strongly hallucinated

## Output Format

You MUST respond with a single valid JSON object:

{
  "hallucination_risk_score": 0,
  "findings": [
    {
      "type": "phantom_import | disconnected_abstraction | duplicate_logic | placeholder_as_complete | inconsistent_naming | unexplained_stack_change",
      "severity": "low | medium | high | critical",
      "description": "string — what the issue is",
      "evidence": "string — what in the diff or memories proves this is a hallucination",
      "affected_files": ["string — file paths with the issue"],
      "code_snippet": "string — the specific code that's problematic"
    }
  ],
  "summary": "string — 1-2 sentence summary of hallucination risk assessment",
  "ai_generation_likelihood": "low | medium | high | very_high"
}

## Guidelines
- Not all AI-generated code is hallucinated. Well-integrated, pattern-consistent AI code should score LOW.
- The key signal is DISCONNECTION from the project, not whether AI wrote it.
- An empty findings array with a low score is perfectly valid for clean changes.
- Be specific in code_snippet — show the actual problematic code, not a vague reference.
- Cross-reference against module roles and dependencies in the provided memories.

Your response must be ONLY the JSON object. No markdown fences, no explanation, just valid JSON.`;

// ── User Message Builder ───────────────────────────────────────────────────────

export interface ModuleRole {
  name: string;
  responsibility: string;
  files: string[];
}

export interface HallucinationDetectionInput {
  diffContent: string;
  filesChanged: { filename: string; status: string }[];
  intentSummary: string;
  changeType: string;
  memories: {
    category: MemoryCategory;
    statement: string;
    importance_score: number;
  }[];
  moduleRoles: ModuleRole[];
  knownDependencies: string[];
  existingImportPaths?: string[];
}

export function buildUserMessage(input: HallucinationDetectionInput): string {
  const sections: string[] = [];

  sections.push(`# Hallucination Detection Request`);

  sections.push(`\n## Change Context`);
  sections.push(`**Intent:** ${input.intentSummary}`);
  sections.push(`**Change Type:** ${input.changeType}`);

  sections.push(`\n## Files Changed`);
  for (const file of input.filesChanged) {
    sections.push(`- \`${file.filename}\` [${file.status}]`);
  }

  sections.push(`\n## Known Dependencies`);
  if (input.knownDependencies.length > 0) {
    sections.push(`These packages are installed and available:`);
    sections.push(input.knownDependencies.map((d) => `\`${d}\``).join(', '));
  } else {
    sections.push(`No dependency list available — be cautious about phantom_import findings.`);
  }

  if (input.existingImportPaths && input.existingImportPaths.length > 0) {
    sections.push(`\n## Known Internal Import Paths`);
    sections.push(`These internal paths exist in the project:`);
    for (const p of input.existingImportPaths.slice(0, 100)) {
      sections.push(`- \`${p}\``);
    }
  }

  sections.push(`\n## Module Roles`);
  if (input.moduleRoles.length > 0) {
    for (const mod of input.moduleRoles) {
      sections.push(`\n### ${mod.name}`);
      sections.push(`Responsibility: ${mod.responsibility}`);
      sections.push(`Files: ${mod.files.join(', ')}`);
    }
  } else {
    sections.push(`No module role information available.`);
  }

  sections.push(`\n## Relevant Memories`);
  if (input.memories.length > 0) {
    for (const mem of input.memories) {
      sections.push(`- [${mem.category}] ${mem.statement}`);
    }
  } else {
    sections.push(`No relevant memories available.`);
  }

  sections.push(`\n## Diff Content`);
  sections.push(`\`\`\`diff\n${truncate(input.diffContent, 20000)}\n\`\`\``);

  sections.push(`\nAnalyze this diff for hallucination indicators. Produce the JSON output described in your instructions.`);

  return sections.join('\n');
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength) + '\n... [truncated]';
}
